
import webpack from 'webpack'
import HtmlWebpackPlugin from 'html-webpack-plugin'
import CircularDependencyPlugin from 'circular-dependency-plugin'
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
import baseConfig from './webpack.base.config'
import ExtractIndexPlugin from './plugins/extract-index-plugin'

module.exports = baseConfig({
  isDebug: true,
  entry: [
    'eventsource-polyfill', // Necessary for hot reloading with IE
    'webpack-hot-middleware/client?reload=true',
  ],
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    // 在编译出现错误时，使用 NoEmitOnErrorsPlugin 来跳过输出阶段。这样可以确保输出资源不会包含错误。对于所有资源，统计资料(stat)的 emitted 标识都是 false。
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackPlugin({
      // title: 'My App',
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: './index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
    new ExtractIndexPlugin({
      opts1: '1'
    }),
    // https://github.com/webpack-contrib/webpack-bundle-analyzer
    // new BundleAnalyzerPlugin(),
  ],
  performance: {
    hints: false,
  },
})
